import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic';

// const {GramMaker} = dynamic(() => import('../components/GramMaker'), {
//   ssr: false,
// })
import { GramMaker } from '../components/GramMaker'

export default function Home() {
  return (<>
      <Head>
        <title>Make a Gram</title>
        <meta name="make a monogram for a photo booth" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='layout-wrap'>

        <header className='header'>
          <h1>{process.env.NEXT_PUBLIC_BRAND_NAME} | Make a Monogram</h1>
        </header>

        <main >
          <GramMaker />
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
  </>)
}
